# CMake build and release workflow
name: CMake Build & Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write   # allow creating and updating releases

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Package build output
      run: |
        mkdir package
        copy build\\${{env.BUILD_TYPE}}\\*.exe package 2>nul || echo "No exe files"
        copy build\\${{env.BUILD_TYPE}}\\*.dll package 2>nul || echo "No dll files"
        copy build\\${{env.BUILD_TYPE}}\\*.pdb package 2>nul || echo "No pdb files"

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: release-${{ github.sha }}
        name: "Build ${{ github.sha }}"
        draft: false
        prerelease: false
        files: package/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

