name: Release Latest Artifact

on:
  workflow_run:
    workflows: ["CMake on a single platform"]   # Name of the workflow that produces the artifact
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from build workflow
        uses: actions/download-artifact@v4
        with:
          name: build-output   # artifact name from the "Build" workflow
          path: ./artifact

      - name: Get version (use commit SHA if no tag)
        id: version
        run: echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ env.VERSION }}
          name: "Nightly Build ${{ env.VERSION }}"
          draft: false
          prerelease: true
          files: ./artifact/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
